# common
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: microservice
          uri: lb://microservice
          predicates:
            - Path=/**
server:
  port: 9000

# discovery server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka