spring:
  application:
    name: microservice
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
server:
  port: 9001
  error:
    include-message: always
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
javainuse:
  rabbitmq:
    routingkey: javainuse.routingkey
    queue: javainuse.queue
    exchange: javainuse.exchange

