# common
spring:
  application:
    name: microservice
  rabbitmq:
    port: '5672'
    host: localhost
    username: guest
    password: guest
server:
  port: 9001
  error:
    include-message: always

# discovery server
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# rabbitmq
test:
  rabbitmq:
    queue: ${listening.queue}
    exchange: distributed.exchange
    sending: ${sending.queue}
    sendingSecond: ${sending.two.queue}
