spring:
  application:
    name: microservice
server:
  port: 9001
  error:
    include-message: always
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka